/**
 * HTML sanitization utility for preventing XSS attacks.
 * RVS-009: Sanitize product descriptions and other user-generated HTML content.
 */
import sanitizeHtmlLib from 'sanitize-html';

const SANITIZE_OPTIONS: sanitizeHtmlLib.IOptions = {
  allowedTags: [
    'a',
    'abbr',
    'address',
    'article',
    'aside',
    'b',
    'blockquote',
    'br',
    'button',
    'caption',
    'cite',
    'code',
    'col',
    'colgroup',
    'data',
    'dd',
    'del',
    'details',
    'dfn',
    'div',
    'dl',
    'dt',
    'em',
    'figcaption',
    'figure',
    'footer',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'header',
    'hr',
    'i',
    'img',
    'ins',
    'kbd',
    'li',
    'main',
    'mark',
    'nav',
    'ol',
    'p',
    'picture',
    'pre',
    'q',
    's',
    'samp',
    'section',
    'small',
    'source',
    'span',
    'strong',
    'sub',
    'summary',
    'sup',
    'table',
    'tbody',
    'td',
    'tfoot',
    'th',
    'thead',
    'time',
    'tr',
    'u',
    'ul',
    'var',
    'video',
    'wbr',
  ],
  allowedAttributes: {
    '*': ['class', 'id', 'style', 'data-*', 'aria-*', 'role'],
    a: ['href', 'target', 'rel', 'title'],
    img: ['src', 'srcset', 'alt', 'title', 'width', 'height', 'loading', 'decoding'],
    source: ['src', 'srcset', 'type', 'media', 'sizes'],
    video: ['src', 'controls', 'autoplay', 'loop', 'muted', 'poster', 'preload', 'width', 'height'],
    button: ['type', 'name', 'value', 'disabled'],
    td: ['colspan', 'rowspan', 'scope', 'headers'],
    th: ['colspan', 'rowspan', 'scope', 'headers'],
    time: ['datetime'],
    details: ['open'],
  },
  disallowedTagsMode: 'discard',
};

/**
 * Sanitize HTML content to prevent XSS attacks.
 * Use this for all user-generated or untrusted HTML content before rendering.
 */
export function sanitizeHtml(html: string): string {
  return sanitizeHtmlLib(html, SANITIZE_OPTIONS);
}
