import type { AIProviderRegistry, ChatMessage } from '@forkcart/ai';
import { createLogger } from '../lib/logger';

const logger = createLogger('product-ai-service');

/** Dependencies for the ProductAIService */
export interface ProductAIServiceDeps {
  aiRegistry: AIProviderRegistry;
}

/** Minimal product data needed for AI generation */
export interface ProductAIInput {
  name: string;
  description?: string | null;
  shortDescription?: string | null;
  sku?: string | null;
  price: number; // in cents
  currency: string;
  categoryNames?: string[];
  attributes?: Record<string, string>;
}

/** SEO metadata generated by AI */
export interface SEOMetadata {
  title: string;
  description: string;
  keywords: string[];
}

/** Bullet points generated by AI */
export interface BulletPoints {
  points: string[];
}

const SYSTEM_PROMPT =
  'You are an e-commerce copywriter. Write compelling, SEO-optimized product descriptions. ' +
  'Write in a professional yet approachable tone. ' +
  'Format the text as HTML with <p> tags for paragraphs. Do NOT use Markdown.';

/**
 * AI service for generating product content.
 * Uses the configured AI provider from the registry.
 */
export class ProductAIService {
  private readonly registry: AIProviderRegistry;

  constructor(deps: ProductAIServiceDeps) {
    this.registry = deps.aiRegistry;
  }

  /** Generate a product description from name, category, and attributes */
  async generateDescription(product: ProductAIInput): Promise<string> {
    const provider = this.getProvider();
    const priceFormatted = `${(product.price / 100).toFixed(2)} ${product.currency}`;

    let prompt = `Write a compelling product description for: "${product.name}"`;
    prompt += `\nPrice: ${priceFormatted}`;
    if (product.categoryNames?.length) {
      prompt += `\nCategory: ${product.categoryNames.join(' > ')}`;
    }
    if (product.attributes && Object.keys(product.attributes).length > 0) {
      prompt += '\nAttributes:';
      for (const [key, value] of Object.entries(product.attributes)) {
        prompt += `\n- ${key}: ${value}`;
      }
    }
    if (product.shortDescription) {
      prompt += `\nShort description: ${product.shortDescription}`;
    }
    prompt += '\n\nWrite 2-3 paragraphs. Format as HTML with <p> tags.';

    const messages: ChatMessage[] = [
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: prompt },
    ];

    logger.info({ productName: product.name }, 'Generating product description');
    const response = await provider.chat(messages, { maxTokens: 800, temperature: 0.8 });
    return response.content;
  }

  /** Generate SEO metadata (title, description, keywords) */
  async generateSEOMetadata(product: ProductAIInput): Promise<SEOMetadata> {
    const provider = this.getProvider();

    const prompt =
      `Generate SEO metadata for the product "${product.name}".` +
      (product.description ? `\nDescription: ${product.description.slice(0, 500)}` : '') +
      '\n\nRespond ONLY with JSON in this format (no explanation):' +
      '\n{"title": "max 60 characters", "description": "max 155 characters", "keywords": ["keyword1", "keyword2", ...]}';

    const messages: ChatMessage[] = [
      {
        role: 'system',
        content: 'You are an SEO specialist for e-commerce. Respond exclusively with valid JSON.',
      },
      { role: 'user', content: prompt },
    ];

    logger.info({ productName: product.name }, 'Generating SEO metadata');
    const response = await provider.chat(messages, { maxTokens: 300, temperature: 0.5 });

    try {
      // Strip markdown code fences if present
      const cleaned = response.content.replace(/```json?\s*/g, '').replace(/```\s*/g, '');
      const parsed = JSON.parse(cleaned) as SEOMetadata;
      return {
        title: String(parsed.title ?? product.name).slice(0, 60),
        description: String(parsed.description ?? '').slice(0, 155),
        keywords: Array.isArray(parsed.keywords) ? parsed.keywords.map(String).slice(0, 10) : [],
      };
    } catch {
      logger.warn('Failed to parse SEO metadata JSON, returning defaults');
      return {
        title: product.name.slice(0, 60),
        description: (product.shortDescription ?? product.name).slice(0, 155),
        keywords: [],
      };
    }
  }

  /** Generate 3-5 selling point bullet points */
  async generateBulletPoints(product: ProductAIInput): Promise<BulletPoints> {
    const provider = this.getProvider();

    const prompt =
      `Create 3-5 compelling selling points (bullet points) for: "${product.name}"` +
      (product.description ? `\nDescription: ${product.description.slice(0, 500)}` : '') +
      '\n\nRespond ONLY with JSON: {"points": ["Point 1", "Point 2", ...]}';

    const messages: ChatMessage[] = [
      {
        role: 'system',
        content:
          'You are an e-commerce copywriter. Write short, punchy selling points. Respond only with JSON.',
      },
      { role: 'user', content: prompt },
    ];

    logger.info({ productName: product.name }, 'Generating bullet points');
    const response = await provider.chat(messages, { maxTokens: 300, temperature: 0.7 });

    try {
      const cleaned = response.content.replace(/```json?\s*/g, '').replace(/```\s*/g, '');
      const parsed = JSON.parse(cleaned) as BulletPoints;
      return {
        points: Array.isArray(parsed.points) ? parsed.points.map(String).slice(0, 5) : [],
      };
    } catch {
      logger.warn('Failed to parse bullet points JSON');
      return { points: [] };
    }
  }

  /** Improve an existing product description */
  async improveDescription(product: ProductAIInput, currentDescription: string): Promise<string> {
    const provider = this.getProvider();

    const prompt =
      `Improve the following product description for "${product.name}":` +
      `\n\n${currentDescription}` +
      '\n\nMake the text more compelling, SEO-optimized, and easier to read.' +
      ' Keep the key messages intact. Format as HTML with <p> tags.';

    const messages: ChatMessage[] = [
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: prompt },
    ];

    logger.info({ productName: product.name }, 'Improving product description');
    const response = await provider.chat(messages, { maxTokens: 800, temperature: 0.7 });
    return response.content;
  }

  /** Get the configured provider or throw */
  private getProvider() {
    const provider = this.registry.getConfiguredProvider();
    if (!provider) {
      throw new Error('No AI provider configured. Configure one in Settings → AI.');
    }
    return provider;
  }
}
