import { randomUUID } from 'node:crypto';
import { resolve, join } from 'node:path';
import { cp, readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import { createLogger } from '../lib/logger';
import type { MobileAppConfig } from './repository';

const logger = createLogger('mobile-app-generator');

/**
 * Generate a customized Expo mobile project from the template.
 * Returns the path to the generated ZIP file.
 */
export async function generateMobileProject(
  config: MobileAppConfig,
  templatePath: string,
  mediaStoragePath: string,
): Promise<string> {
  const tmpDir = resolve('/tmp', `forkcart-mobile-${randomUUID()}`);
  const projectDir = join(tmpDir, 'forkcart-mobile');

  try {
    // 1. Copy template to tmp directory
    logger.info({ templatePath, tmpDir }, 'Copying mobile template');
    await mkdir(tmpDir, { recursive: true });
    await cp(templatePath, projectDir, {
      recursive: true,
      filter: (src) => {
        // Skip node_modules and .expo
        const name = src.split('/').pop() ?? '';
        return name !== 'node_modules' && name !== '.expo';
      },
    });

    // 2. Read and update app.json
    const appJsonPath = join(projectDir, 'app.json');
    let appJsonContent: string;
    try {
      appJsonContent = await readFile(appJsonPath, 'utf-8');
    } catch {
      // If no app.json, create a default one
      appJsonContent = JSON.stringify(
        {
          expo: {
            name: '{{APP_NAME}}',
            slug: '{{APP_SLUG}}',
            extra: {
              apiUrl: '',
              primaryColor: '#000000',
              accentColor: '#FF6B00',
            },
          },
        },
        null,
        2,
      );
    }

    // Replace placeholders
    appJsonContent = appJsonContent
      .replace(/\{\{APP_NAME\}\}/g, config.appName)
      .replace(/\{\{APP_SLUG\}\}/g, config.appSlug);

    // Parse, update deep values, and write back
    const appJson = JSON.parse(appJsonContent);
    const expo = appJson.expo ?? appJson;

    expo.name = config.appName;
    expo.slug = config.appSlug;

    // Set extra config — must be under `forkcart` key to match mobile lib/config.ts
    expo.extra = {
      ...(expo.extra ?? {}),
      forkcart: {
        ...(expo.extra?.forkcart ?? {}),
        apiUrl: config.apiUrl,
        storeName: config.appName,
        primaryColor: config.primaryColor,
        accentColor: config.accentColor,
        backgroundColor: config.backgroundColor,
        currency: 'EUR',
        currencyLocale: 'de-DE',
      },
    };

    // Set bundle identifiers if provided
    if (config.bundleId) {
      expo.ios = { ...(expo.ios ?? {}), bundleIdentifier: config.bundleId };
    }
    if (config.androidPackage) {
      expo.android = { ...(expo.android ?? {}), package: config.androidPackage };
    }

    await writeFile(appJsonPath, JSON.stringify(appJson, null, 2), 'utf-8');

    // 3. Copy icon if uploaded
    if (config.iconMediaId) {
      try {
        // Try to find the media file in storage
        const iconFiles = await findMediaFile(mediaStoragePath, config.iconMediaId);
        if (iconFiles) {
          const assetsDir = join(projectDir, 'assets');
          await mkdir(assetsDir, { recursive: true });
          await cp(iconFiles, join(assetsDir, 'icon.png'));
        }
      } catch (err) {
        logger.warn({ err, mediaId: config.iconMediaId }, 'Could not copy icon');
      }
    }

    // 4. Copy splash if uploaded
    if (config.splashMediaId) {
      try {
        const splashFiles = await findMediaFile(mediaStoragePath, config.splashMediaId);
        if (splashFiles) {
          const assetsDir = join(projectDir, 'assets');
          await mkdir(assetsDir, { recursive: true });
          await cp(splashFiles, join(assetsDir, 'splash.png'));
        }
      } catch (err) {
        logger.warn({ err, mediaId: config.splashMediaId }, 'Could not copy splash');
      }
    }

    // 5. Create a theme config file the app can import
    const themeConfig = `// Auto-generated by ForkCart App Builder
export const theme = {
  primaryColor: '${config.primaryColor}',
  accentColor: '${config.accentColor}',
  backgroundColor: '${config.backgroundColor}',
  appName: '${config.appName.replace(/'/g, "\\'")}',
  apiUrl: '${config.apiUrl}',
};
`;
    await writeFile(join(projectDir, 'theme.config.ts'), themeConfig, 'utf-8');

    // 6. ZIP the directory
    const archiver = await import('archiver');
    const { createWriteStream } = await import('node:fs');

    const zipPath = join(tmpDir, 'forkcart-mobile.zip');
    const output = createWriteStream(zipPath);
    const archive = archiver.default('zip', { zlib: { level: 9 } });

    await new Promise<void>((resolvePromise, reject) => {
      output.on('close', resolvePromise);
      archive.on('error', reject);
      archive.pipe(output);
      archive.directory(projectDir, 'forkcart-mobile');
      archive.finalize();
    });

    logger.info({ zipPath, size: archive.pointer() }, 'Mobile project ZIP created');
    return zipPath;
  } catch (err) {
    // Cleanup on error
    await rm(tmpDir, { recursive: true, force: true }).catch(() => {});
    throw err;
  }
}

/** Clean up a generated project directory */
export async function cleanupGeneratedProject(zipPath: string): Promise<void> {
  // The zip is in /tmp/forkcart-mobile-{uuid}/forkcart-mobile.zip
  // Remove the parent directory
  const tmpDir = resolve(zipPath, '..');
  await rm(tmpDir, { recursive: true, force: true }).catch(() => {});
}

/** Try to find a media file by its ID in the storage path */
async function findMediaFile(storagePath: string, mediaId: string): Promise<string | null> {
  const { readdir } = await import('node:fs/promises');

  try {
    const files = await readdir(storagePath);
    // Media files are typically stored as {uuid}.{ext} or in subdirectories
    const match = files.find((f) => f.startsWith(mediaId));
    if (match) return join(storagePath, match);
  } catch {
    // storage path may not exist
  }

  return null;
}
