#!/usr/bin/env node
/**
 * Auto-discover locale files in locales/ and generate TypeScript index.
 * Also validates that all locales have the same keys as en.json (warns on missing).
 *
 * Run: node scripts/build-locales.js
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const LOCALES_DIR = resolve(__dirname, '../locales');
const OUT_FILE = resolve(__dirname, '../src/_locales.generated.ts');

/** Recursively collect all keys from a nested object */
function collectKeys(obj, prefix = '') {
  const keys = [];
  for (const [key, value] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}.${key}` : key;
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      keys.push(...collectKeys(value, fullKey));
    } else {
      keys.push(fullKey);
    }
  }
  return keys;
}

// Scan for storefront locales (xx.json, not admin-xx.json)
const allFiles = readdirSync(LOCALES_DIR).filter((f) => f.endsWith('.json'));
const storefrontFiles = allFiles.filter((f) => !f.startsWith('admin-'));
const adminFiles = allFiles.filter((f) => f.startsWith('admin-'));

const storefrontLocales = storefrontFiles.map((f) => f.replace('.json', ''));
const adminLocales = adminFiles.map((f) => f.replace('admin-', '').replace('.json', ''));

console.log(`[i18n] Storefront locales: ${storefrontLocales.join(', ')}`);
console.log(`[i18n] Admin locales: ${adminLocales.join(', ')}`);

// ── Validate missing keys ──────────────────────────────────────────────

let warnings = 0;

function validateAgainstBase(baseFile, files, dir, prefix) {
  const basePath = resolve(dir, baseFile);
  if (!allFiles.includes(baseFile)) return;

  const baseData = JSON.parse(readFileSync(basePath, 'utf-8'));
  const baseKeys = collectKeys(baseData);

  for (const file of files) {
    if (file === baseFile) continue;
    const filePath = resolve(dir, file);
    const data = JSON.parse(readFileSync(filePath, 'utf-8'));
    const fileKeys = new Set(collectKeys(data));

    const missing = baseKeys.filter((k) => !fileKeys.has(k));
    if (missing.length > 0) {
      warnings += missing.length;
      console.warn(`\n⚠️  ${prefix}${file} is missing ${missing.length} key(s):`);
      for (const k of missing.slice(0, 15)) {
        console.warn(`   - ${k}`);
      }
      if (missing.length > 15) {
        console.warn(`   ... and ${missing.length - 15} more`);
      }
    }
  }
}

validateAgainstBase('en.json', storefrontFiles, LOCALES_DIR, '');
validateAgainstBase('admin-en.json', adminFiles, LOCALES_DIR, '');

if (warnings > 0) {
  console.warn(
    `\n⚠️  Total: ${warnings} missing translation(s). Fallback to English will be used.\n`,
  );
} else {
  console.log('[i18n] ✓ All translations complete');
}

// ── Generate TypeScript file ───────────────────────────────────────────

const lines = [
  '// AUTO-GENERATED by scripts/build-locales.js — DO NOT EDIT',
  '// Re-run: pnpm --filter @forkcart/i18n run build',
  `// Generated: ${new Date().toISOString()}`,
  '',
  "import type { TranslationDict } from './index';",
  '',
];

// Storefront imports
for (const loc of storefrontLocales) {
  lines.push(`import ${loc}Storefront from '../locales/${loc}.json';`);
}

// Admin imports
for (const loc of adminLocales) {
  lines.push(`import ${loc}Admin from '../locales/admin-${loc}.json';`);
}

lines.push('');

// Storefront exports
lines.push('export const storefrontTranslations: Record<string, TranslationDict> = {');
for (const loc of storefrontLocales) {
  lines.push(`  ${loc}: ${loc}Storefront as unknown as TranslationDict,`);
}
lines.push('};');
lines.push('');

lines.push(`export const storefrontLocales: string[] = ${JSON.stringify(storefrontLocales)};`);
lines.push('');

// Admin exports
lines.push('export const adminTranslations: Record<string, TranslationDict> = {');
for (const loc of adminLocales) {
  lines.push(`  ${loc}: ${loc}Admin as unknown as TranslationDict,`);
}
lines.push('};');
lines.push('');

lines.push(`export const adminLocales: string[] = ${JSON.stringify(adminLocales)};`);
lines.push('');

writeFileSync(OUT_FILE, lines.join('\n'));
console.log(`[i18n] Generated ${OUT_FILE}`);
