// AUTO-GENERATED by scripts/build-locales.js — DO NOT EDIT
// Re-run: pnpm --filter @forkcart/i18n run build
// Generated: 2026-04-18T10:32:09.427Z

import type { TranslationDict } from './index';

import deStorefront from '../locales/de.json';
import enStorefront from '../locales/en.json';
import deAdmin from '../locales/admin-de.json';
import enAdmin from '../locales/admin-en.json';

export const storefrontTranslations: Record<string, TranslationDict> = {
  de: deStorefront as unknown as TranslationDict,
  en: enStorefront as unknown as TranslationDict,
};

export const storefrontLocales: string[] = ["de","en"];

export const adminTranslations: Record<string, TranslationDict> = {
  de: deAdmin as unknown as TranslationDict,
  en: enAdmin as unknown as TranslationDict,
};

export const adminLocales: string[] = ["de","en"];
